<?php

// 50 actions.
$as_actions = [
    [
        'name' => '"action_scheduler_failed_{$context}_action_deletion"',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_QueueCleaner.php',
        'type' => 'action',
        'args' => 4,
    ],
    [
        'name' => '$hook',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\actions\\ActionScheduler_Action.php',
        'type' => 'action_reference',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler/created_table\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_Schema.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler/migrate_action_dry_run\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\DryRun_ActionMigrator.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler/migrate_action_failed\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\ActionMigrator.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler/migrate_action_incomplete\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\ActionMigrator.php',
        'type' => 'action',
        'args' => 4,
    ],
    [
        'name' => '\'action_scheduler/migrated_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\ActionMigrator.php',
        'type' => 'action',
        'args' => 4,
    ],
    [
        'name' => '\'action_scheduler/migrated_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\ActionMigrator.php',
        'type' => 'action',
        'args' => 4,
    ],
    [
        'name' => '\'action_scheduler/migration_batch_complete\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\Runner.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler/migration_batch_starting\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\Runner.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler/migration_complete\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\Scheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler/no_action_to_migrate\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\migration\\ActionMigrator.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler/progress_tick\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\WP_CLI\\ProgressBar.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_after_execute\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler_after_process_queue\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_QueueRunner.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_after_process_queue\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\WP_CLI\\ActionScheduler_WPCLI_QueueRunner.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_before_execute\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_before_process_queue\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_QueueRunner.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_before_process_queue\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\WP_CLI\\ActionScheduler_WPCLI_QueueRunner.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_before_schema_update\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_Schema.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_begin_execute\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_bulk_cancel_actions\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Store.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_bulk_cancel_actions\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_canceled_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_canceled_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_wpPostStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_completed_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_completed_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_wpPostStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_deleted_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_deleted_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_wpPostStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_ensure_recurring_actions\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_RecurringActionScheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_execution_ignored\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_failed_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_QueueCleaner.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_failed_execution\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler_failed_fetch_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_failed_fetch_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_wpPostStore.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_failed_to_schedule_next_instance\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler_failed_to_schedule_next_instance\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\tests\\phpunit\\logging\\ActionScheduler_wpCommentLogger_Test.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler_failed_validation\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler_Abstract_QueueRunner.php',
        'type' => 'action',
        'args' => 3,
    ],
    [
        'name' => '\'action_scheduler_init\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_init\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_pastdue_actions_extra_notices\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_AdminView.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_pre_init\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\abstracts\\ActionScheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_pre_theme_init\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\action-scheduler.php',
        'type' => 'action',
        'args' => 0,
    ],
    [
        'name' => '\'action_scheduler_reset_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_QueueCleaner.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_run_queue\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_AsyncRequest_QueueRunner.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_stored_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_DBStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_stored_action\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\data-stores\\ActionScheduler_wpPostStore.php',
        'type' => 'action',
        'args' => 1,
    ],
    [
        'name' => '\'action_scheduler_unexpected_shutdown\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\classes\\ActionScheduler_FatalErrorMonitor.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_unexpected_shutdown\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\tests\\phpunit\\logging\\ActionScheduler_DBLogger_Test.php',
        'type' => 'action',
        'args' => 2,
    ],
    [
        'name' => '\'action_scheduler_unexpected_shutdown\'',
        'file' => 'D:\\CloudSync\\0-Dev\\wp-projects\\base-projects\\action-scheduler\\tests\\phpunit\\logging\\ActionScheduler_wpCommentLogger_Test.php',
        'type' => 'action',
        'args' => 2,
    ],
];
