<?php

$woocommerce_dynamic_actions = [
    '0.' => [
        'name' => 'added_{$this->object_type}_meta',
        'norm_name' => 'added_{$var}_meta',
        'prefix' => 'added_',
        'suffix' => '_meta',
    ],
    '1.' => [
        'name' => 'deleted_{$this->object_type}_meta',
        'norm_name' => 'deleted_{$var}_meta',
        'prefix' => 'deleted_',
        'suffix' => '_meta',
    ],
    '2.' => [
        'name' => 'updated_{$this->object_type}_meta',
        'norm_name' => 'updated_{$var}_meta',
        'prefix' => 'updated_',
        'suffix' => '_meta',
    ],
    '3.' => [
        'name' => 'woocommerce_account_downloads_column_{$column_id}',
        'norm_name' => 'woocommerce_account_downloads_column_{$var}',
        'prefix' => 'woocommerce_account_downloads_column_',
        'suffix' => '',
    ],
    '4.' => [
        'name' => 'woocommerce_account_payment_methods_column_{$column_id}',
        'norm_name' => 'woocommerce_account_payment_methods_column_{$var}',
        'prefix' => 'woocommerce_account_payment_methods_column_',
        'suffix' => '',
    ],
    '5.' => [
        'name' => 'woocommerce_account_{$key}_endpoint',
        'norm_name' => 'woocommerce_account_{$var}_endpoint',
        'prefix' => 'woocommerce_account_',
        'suffix' => '_endpoint',
    ],
    '6.' => [
        'name' => 'woocommerce_admin_status_content_{$current_tab}',
        'norm_name' => 'woocommerce_admin_status_content_{$var}',
        'prefix' => 'woocommerce_admin_status_content_',
        'suffix' => '',
    ],
    '7.' => [
        'name' => 'woocommerce_after_edit_address_form_{$load_address}',
        'norm_name' => 'woocommerce_after_edit_address_form_{$var}',
        'prefix' => 'woocommerce_after_edit_address_form_',
        'suffix' => '',
    ],
    '8.' => [
        'name' => 'woocommerce_after_settings_{$current_tab}',
        'norm_name' => 'woocommerce_after_settings_{$var}',
        'prefix' => 'woocommerce_after_settings_',
        'suffix' => '',
    ],
    '9.' => [
        'name' => 'woocommerce_after_{$this->object_type}_object_save',
        'norm_name' => 'woocommerce_after_{$var}_object_save',
        'prefix' => 'woocommerce_after_',
        'suffix' => '_object_save',
    ],
    '10.' => [
        'name' => 'woocommerce_api_process_product_meta_{$product->get_type()}',
        'norm_name' => 'woocommerce_api_process_product_meta_{$var}',
        'prefix' => 'woocommerce_api_process_product_meta_',
        'suffix' => '',
    ],
    '11.' => [
        'name' => 'woocommerce_before_edit_address_form_{$load_address}',
        'norm_name' => 'woocommerce_before_edit_address_form_{$var}',
        'prefix' => 'woocommerce_before_edit_address_form_',
        'suffix' => '',
    ],
    '12.' => [
        'name' => 'woocommerce_before_order_item_{$item->get_type()}_html',
        'norm_name' => 'woocommerce_before_order_item_{$var}_html',
        'prefix' => 'woocommerce_before_order_item_',
        'suffix' => '_html',
    ],
    '13.' => [
        'name' => 'woocommerce_before_settings_{$current_tab}',
        'norm_name' => 'woocommerce_before_settings_{$var}',
        'prefix' => 'woocommerce_before_settings_',
        'suffix' => '',
    ],
    '14.' => [
        'name' => 'woocommerce_before_{$this->object_type}_object_save',
        'norm_name' => 'woocommerce_before_{$var}_object_save',
        'prefix' => 'woocommerce_before_',
        'suffix' => '_object_save',
    ],
    '15.' => [
        'name' => 'woocommerce_download_file_{$file_download_method}',
        'norm_name' => 'woocommerce_download_file_{$var}',
        'prefix' => 'woocommerce_download_file_',
        'suffix' => '',
    ],
    '16.' => [
        'name' => 'woocommerce_email_downloads_column_{$column_id}',
        'norm_name' => 'woocommerce_email_downloads_column_{$var}',
        'prefix' => 'woocommerce_email_downloads_column_',
        'suffix' => '',
    ],
    '17.' => [
        'name' => 'woocommerce_email_setting_column_{$key}',
        'norm_name' => 'woocommerce_email_setting_column_{$var}',
        'prefix' => 'woocommerce_email_setting_column_',
        'suffix' => '',
    ],
    '18.' => [
        'name' => 'woocommerce_grouped_product_list_after_{$column_id}',
        'norm_name' => 'woocommerce_grouped_product_list_after_{$var}',
        'prefix' => 'woocommerce_grouped_product_list_after_',
        'suffix' => '',
    ],
    '19.' => [
        'name' => 'woocommerce_grouped_product_list_before_{$column_id}',
        'norm_name' => 'woocommerce_grouped_product_list_before_{$var}',
        'prefix' => 'woocommerce_grouped_product_list_before_',
        'suffix' => '',
    ],
    '20.' => [
        'name' => 'woocommerce_my_account_my_orders_column_{$column_id}',
        'norm_name' => 'woocommerce_my_account_my_orders_column_{$var}',
        'prefix' => 'woocommerce_my_account_my_orders_column_',
        'suffix' => '',
    ],
    '21.' => [
        'name' => 'woocommerce_order_item_{$item->get_type()}_html',
        'norm_name' => 'woocommerce_order_item_{$var}_html',
        'prefix' => 'woocommerce_order_item_',
        'suffix' => '_html',
    ],
    '22.' => [
        'name' => 'woocommerce_receipt_{$order->get_payment_method()}',
        'norm_name' => 'woocommerce_receipt_{$var}',
        'prefix' => 'woocommerce_receipt_',
        'suffix' => '',
    ],
    '23.' => [
        'name' => 'woocommerce_rest_delete_{$this->post_type}',
        'norm_name' => 'woocommerce_rest_delete_{$var}',
        'prefix' => 'woocommerce_rest_delete_',
        'suffix' => '',
    ],
    '24.' => [
        'name' => 'woocommerce_rest_delete_{$this->post_type}_object',
        'norm_name' => 'woocommerce_rest_delete_{$var}_object',
        'prefix' => 'woocommerce_rest_delete_',
        'suffix' => '_object',
    ],
    '25.' => [
        'name' => 'woocommerce_rest_insert_{$this->post_type}',
        'norm_name' => 'woocommerce_rest_insert_{$var}',
        'prefix' => 'woocommerce_rest_insert_',
        'suffix' => '',
    ],
    '26.' => [
        'name' => 'woocommerce_rest_insert_{$this->post_type}_object',
        'norm_name' => 'woocommerce_rest_insert_{$var}_object',
        'prefix' => 'woocommerce_rest_insert_',
        'suffix' => '_object',
    ],
    '27.' => [
        'name' => 'woocommerce_sections_{$current_tab}',
        'norm_name' => 'woocommerce_sections_{$var}',
        'prefix' => 'woocommerce_sections_',
        'suffix' => '',
    ],
    '28.' => [
        'name' => 'woocommerce_settings_tabs_{$current_tab}',
        'norm_name' => 'woocommerce_settings_tabs_{$var}',
        'prefix' => 'woocommerce_settings_tabs_',
        'suffix' => '',
    ],
    '29.' => [
        'name' => 'woocommerce_settings_{$current_tab}',
        'norm_name' => 'woocommerce_settings_{$var}',
        'prefix' => 'woocommerce_settings_',
        'suffix' => '',
    ],
    '30.' => [
        'name' => 'woocommerce_shipping_classes_column_{$class}',
        'norm_name' => 'woocommerce_shipping_classes_column_{$var}',
        'prefix' => 'woocommerce_shipping_classes_column_',
        'suffix' => '',
    ],
    '31.' => [
        'name' => 'woocommerce_thankyou_{$order->get_payment_method()}',
        'norm_name' => 'woocommerce_thankyou_{$var}',
        'prefix' => 'woocommerce_thankyou_',
        'suffix' => '',
    ],
    '32.' => [
        'name' => 'woocommerce_update_options_{$this->id}_',
        'norm_name' => 'woocommerce_update_options_{$var}_',
        'prefix' => 'woocommerce_update_options_',
        'suffix' => '_',
    ],
    '33.' => [
        'name' => 'woocommerce_{$this->id}_shipping_add_rate',
        'norm_name' => 'woocommerce_{$var}_shipping_add_rate',
        'prefix' => 'woocommerce_',
        'suffix' => '_shipping_add_rate',
    ],
    '34.' => [
        'name' => 'wp_{$blog_id}_wc_updater_cron',
        'norm_name' => 'wp_{$var}_wc_updater_cron',
        'prefix' => 'wp_',
        'suffix' => '_wc_updater_cron',
    ],
];
